version: '3.8'

services:
  project:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prj
    image: project:0.0.1
    container_name: project
    environment:
      - BASIC_SERVER_PORT=8090
      - DATABASE_URL=postgresql://Mover:aboba@db:5432/KeyValueStorage
    ports:
      - "8090:8090"
    volumes:
      - ./data:/app/data/
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "KeyValueStorage"
      POSTGRES_USER: "Mover"
      POSTGRES_PASSWORD: "aboba"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  data:
